dh_frame_list:
 dh_0:
  id: 0
  name: 'r_arm_joint_0'
 dh_1:
  id: 1
  name: 'r_arm_joint_1'
 dh_2:
  id: 2
  name: 'r_arm_joint_2'
 dh_3:
  id: 3
  name: 'r_arm_joint_3'
 dh_4:
  id: 4
  name: 'r_arm_joint_4'
 dh_5:
  id: 5
  name: 'r_arm_joint_5'
 dh_6:
  id: 6
  name: 'r_arm_joint_6'

